apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tanzuoyo-pvc
  namespace: default
  labels:
    type: vsphere
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  storageClassName: ""
#  volumeMode: Filesystem
