apiVersion: v1
kind: PersistentVolume
metadata:
  name: tanzuoyo-pv
  namespace: default
  labels:
    type: vsphere
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/tanzuoyo
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # none.  Blank is default.
