apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tanzuoyo-pvc
  namespace: default
  labels:
    type: vsphere
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: "" # None.  Blank is default
